import Link from 'next/link';
import { BreadcrumbJsonLd, ServiceJsonLd } from '@/components/SeoJsonLd';
import { pageMetadata } from '@/lib/seo';

const path='/psicoterapia-giovani-adulti-catania';
const description='Psicoterapia per giovani adulti a Catania: ansia, blocchi, relazioni, procrastinazione, scelte e costruzione dell’identità.';

export const metadata=pageMetadata({title:'Psicoterapia giovani adulti a Catania',description,path});

export default function Page(){return <>
<BreadcrumbJsonLd items={[{name:'Home',path:'/'},{name:'Aree di intervento',path:'/aree-di-intervento'},{name:'Giovani adulti',path}]} />
<ServiceJsonLd name="Psicoterapia per giovani adulti" description={description} path={path} audience="Giovani adulti" />
<section className="page-hero"><div className="container narrow"><span className="eyebrow">Psicoterapia giovani adulti a Catania</span><h1>Giovani adulti: quando il passaggio alla vita adulta diventa un punto di blocco.</h1><p className="lead">L’ingresso nella vita adulta porta scelte, cambiamenti, relazioni, lavoro, studio e responsabilità che possono mettere in discussione l’immagine che abbiamo di noi stessi. Non sempre il disagio assume la forma di un sintomo preciso: a volte è una sensazione persistente di essere fermi, disorganizzati o scollegati da ciò che si desidera.</p></div></section><section className="section"><div className="container prose"><h2>Come può manifestarsi nella vita quotidiana</h2><p>Possono comparire ansia, difficoltà decisionali, relazioni instabili, autocritica, procrastinazione, fatica nel definire priorità o un senso di distanza tra ciò che si pensa di “dover essere” e ciò che realmente si sente.</p><h2>Quando può essere utile chiedere una consulenza</h2><p>Può essere utile confrontarsi con un professionista quando la difficoltà tende a ripetersi, limita scelte importanti, produce sofferenza significativa o quando i tentativi messi in atto non stanno portando il cambiamento desiderato. Un primo colloquio non implica automaticamente l’avvio di una psicoterapia: serve prima di tutto a comprendere la situazione.</p><h2>Come lavoro</h2><p>La psicoterapia aiuta a ricostruire i processi che mantengono il blocco e a distinguere aspettative, bisogni, strategie di protezione e possibilità concrete di cambiamento.</p><div className="note"><strong>Approccio personalizzato</strong><p>La pagina descrive situazioni frequenti, non è uno strumento di autodiagnosi. La valutazione clinica riguarda sempre il funzionamento della singola persona.</p></div><Link className="btn" href="/contatti">Richiedi un primo colloquio</Link></div></section></>}
