import Image from 'next/image';
import Link from 'next/link';
import { BreadcrumbJsonLd } from '@/components/SeoJsonLd';
import { pageMetadata } from '@/lib/seo';
import { site } from '@/lib/site';

export const metadata = pageMetadata({
  title: 'Chi sono',
  description: 'Francesco Corsaro, psicologo e psicoterapeuta a Catania. Formazione in Psicoterapia Cognitiva Complessa ed esperienza con adolescenti e neurodivergenze.',
  path: '/chi-sono'
});

export default function Page(){const hasVat=!site.vat.startsWith('['); return <>
<BreadcrumbJsonLd items={[{name:'Home',path:'/'},{name:'Chi sono',path:'/chi-sono'}]} />
<section className="page-hero"><div className="container narrow"><span className="eyebrow">Chi sono</span><h1>Prima della tecnica viene la comprensione della persona.</h1><p className="lead">Sono Francesco Corsaro, psicologo e psicoterapeuta a Catania. Lavoro con adolescenti, giovani adulti e genitori, con particolare attenzione ad ansia, ADHD, autismo e processi di regolazione emotiva.</p></div></section><section className="section"><div className="container about-grid"><figure className="about-photo"><Image src={site.photo} alt="Francesco Corsaro, psicologo e psicoterapeuta" fill sizes="(max-width: 900px) 100vw, 42vw" className="portrait-image" /></figure><div className="prose"><h2>Come lavoro</h2><p>Quando una persona arriva in terapia porta spesso un problema molto concreto: ansia che limita, difficoltà a organizzarsi, conflitti, stanchezza emotiva, sensazione di blocco. Il mio lavoro parte da lì, ma non si ferma alla descrizione del sintomo.</p><p>Mi interessa capire come quella difficoltà si è costruita, cosa la mantiene e che funzione hanno le strategie che la persona utilizza per affrontarla. Anche comportamenti che oggi sembrano poco utili possono essere stati, in altri momenti, tentativi comprensibili di adattamento.</p><h2>Formazione</h2><p>Sono laureato in Psicologia Clinica, psicologo e psicoterapeuta. Ho completato la formazione quadriennale in Psicoterapia Cognitiva Complessa presso la Scuola ALETEIA.</p><p>La mia esperienza professionale comprende il lavoro con adolescenti, persone con ADHD e disturbi del neurosviluppo, persone autistiche e famiglie. Ho maturato esperienza anche in contesti educativi e in interventi strutturati e comportamentali, mantenendo un’attenzione costante alla singolarità della persona e al contesto.</p><h2>Interessi clinici</h2><p>Approfondisco in particolare i rapporti tra psicoterapia, neuroscienze, psicofisiologia, attaccamento e processi di autoregolazione. Questi riferimenti non vengono usati per complicare il linguaggio della terapia, ma per formulare domande più precise su ciò che accade.</p><div className="note"><strong>Informazioni professionali</strong><p>Iscritto all’Ordine degli Psicologi della Regione Siciliana, n. {site.orderNumber}.</p>{hasVat && <p>Partita IVA: {site.vat}.</p>}</div><Link className="btn" href="/contatti">Richiedi un primo colloquio</Link></div></div></section></>}
