import Link from 'next/link';
import { BreadcrumbJsonLd, ServiceJsonLd } from '@/components/SeoJsonLd';
import { pageMetadata } from '@/lib/seo';

const path='/psicologo-adhd-catania';
const description='Supporto psicologico per ADHD a Catania: attenzione, funzioni esecutive, procrastinazione, gestione del tempo e regolazione emotiva.';

export const metadata=pageMetadata({title:'Psicologo ADHD a Catania',description,path});

export default function Page(){return <>
<BreadcrumbJsonLd items={[{name:'Home',path:'/'},{name:'Aree di intervento',path:'/aree-di-intervento'},{name:'ADHD',path}]} />
<ServiceJsonLd name="Supporto psicologico per ADHD" description={description} path={path} audience="Adolescenti e adulti" />
<section className="page-hero"><div className="container narrow"><span className="eyebrow">Psicologo ADHD a Catania</span><h1>ADHD: non è soltanto una questione di concentrazione.</h1><p className="lead">L’ADHD può coinvolgere attenzione, funzioni esecutive, gestione del tempo, avvio dei compiti, memoria di lavoro, impulsività e regolazione emotiva. Molte difficoltà emergono soprattutto quando le richieste della vita aumentano e l’organizzazione deve diventare più autonoma.</p></div></section><section className="section"><div className="container prose"><h2>Come può manifestarsi nella vita quotidiana</h2><p>Può manifestarsi nel rimandare anche attività importanti, sottostimare i tempi, iniziare molte cose e terminarne poche, vivere oscillazioni tra iperfocus e blocco, reagire intensamente alle frustrazioni o sentirsi costantemente “in ritardo” rispetto a ciò che si vorrebbe fare.</p><h2>Quando può essere utile chiedere una consulenza</h2><p>Può essere utile confrontarsi con un professionista quando la difficoltà tende a ripetersi, limita scelte importanti, produce sofferenza significativa o quando i tentativi messi in atto non stanno portando il cambiamento desiderato. Un primo colloquio non implica automaticamente l’avvio di una psicoterapia: serve prima di tutto a comprendere la situazione.</p><h2>Come lavoro</h2><p>Il lavoro parte dal funzionamento reale della persona e dai contesti in cui le difficoltà diventano più evidenti. Si lavora su strategie di organizzazione, consapevolezza dei pattern, regolazione emotiva, gestione dell’ambiente e riduzione di quei cicli di autocritica che possono aggravare il problema.</p><div className="note"><strong>Approccio personalizzato</strong><p>La pagina descrive situazioni frequenti, non è uno strumento di autodiagnosi. La valutazione clinica riguarda sempre il funzionamento della singola persona.</p></div><Link className="btn" href="/contatti">Richiedi un primo colloquio</Link></div></section></>}
