import type { Metadata } from 'next';
export const metadata: Metadata = { title:'FAQ', description:'Domande frequenti su primo colloquio, psicoterapia, adolescenti, parent training, ADHD e orientamento terapeutico.', alternates:{canonical:'/faq'}, openGraph:{title:'FAQ | Francesco Corsaro',description:'Domande frequenti su primo colloquio, psicoterapia, adolescenti, ADHD e parent training.'} };
const faqs=[
['Come funziona il primo colloquio?','Serve a comprendere il motivo della richiesta, cosa sta accadendo in questo momento e quali aspetti meritano di essere approfonditi. È anche uno spazio per capire se il modo di lavorare proposto può essere adatto alla situazione.'],
['Quanto dura una seduta?','[DA INSERIRE: durata reale della seduta.]'],
['Quanto dura una psicoterapia?','Non esiste una durata uguale per tutti. Dipende dalla richiesta, dagli obiettivi, dalla complessità del problema e dall’andamento del percorso. Tempi e modalità vengono discussi e rivalutati nel corso del lavoro.'],
['Lavori anche con adolescenti?','Sì. Il lavoro con gli adolescenti tiene conto non solo della difficoltà riportata, ma anche della fase di sviluppo, della scuola, delle relazioni, dell’autonomia e del contesto familiare.'],
['Come funziona il coinvolgimento dei genitori nella terapia di un adolescente?','Dipende dall’età, dalla richiesta e dalla situazione. Il coinvolgimento dei genitori viene definito rispettando il percorso dell’adolescente e la necessità di mantenere una cornice clinica chiara. [DA COMPLETARE con la procedura abituale adottata nello studio.]'],
['Che cos’è il parent training?','È un lavoro rivolto ai genitori per comprendere meglio le dinamiche che mantengono una difficoltà e costruire strategie educative e relazionali più efficaci. Non è una ricerca di colpe o “errori educativi”.'],
['Ti occupi di ADHD negli adulti?','Il sito è predisposto per indicare il lavoro con giovani adulti e difficoltà riconducibili all’ADHD. [DA CONFERMARE: presa in carico specifica di adulti con ADHD e limiti di età.]'],
['È necessario avere già una diagnosi?','No. Una persona può chiedere un primo colloquio anche partendo da una difficoltà concreta, senza avere già una diagnosi. Quando necessario, si può valutare il percorso più appropriato.'],
['Qual è il tuo orientamento psicoterapeutico?','Psicoterapia Cognitiva Complessa, con riferimenti al cognitivismo, costruttivismo, psicologia dello sviluppo, sistemi complessi, psicofisiologia e neuroscienze.']
];
export default function Page(){return <><section className="page-hero"><div className="container narrow"><span className="eyebrow">FAQ</span><h1>Domande frequenti prima di iniziare.</h1><p className="lead">Informazioni concrete per capire come funziona il primo contatto e come viene impostato il lavoro.</p></div></section><section className="section"><div className="container faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section></>}
